error: add error infrastructure for PEL creation
Introduced use of ErrlEntry, ErrlHandle, and ErrlFactory to represent
and propagate detailed error information. All failure paths now return
error objects instead of raw codes, enabling consistent FFDC capture
and centralized PEL creation logic. This simplifies error handling and
eliminates duplication across repositories.

Test:
"User Data 2": {
    "Section Version":          "1",
    "Sub-section type":         "1",
    "Created by":               "0x4500",
    "Data": [
        "00 00 00 00 7A 95 10 49  FF 00 00 00 00 00 00 04  |  ....z..I........",
        "00 04 10 38 00 02 00 00  53 42 45 5F 54 52 41 43  |  ...8....SBE_TRAC",
        "45 00 00 00 00 00 00 00  00 00 30 0F 38 13 10 00  |  E.........0.8...",
        "FE 23 29 AF 23 C3 46 00  00 00 00 00 FF FF FF FF  |  .#).#.F.........",
        "EF 73 FA 8F 00 00 00 18  00 01 5F D8 00 00 00 00  |  .s........_.....",
        "00 00 00 00 2C 8D 01 01  9D 5C 3E 06 5F D6 00 00  |  ....,....\\>._...",
        "9D 5C 43 11 A6 39 00 06  9F 4D 53 A9 00 00 DA 7A  |  .\\C..9...MS....z",
        "00 00 00 00 D0 A4 01 02  9F 4D 56 1E 00 00 00 00  |  .........MV.....",
        "00 00 00 01 C4 9C 01 02  9F 4D 58 DA 91 A0 00 06  |  .........MX.....",
        "9F 4D 5A F1 C9 20 00 00  9F 4D 60 21 00 00 00 01  |  .MZ.. ...M`!....",
        "00 00 00 00 EB 80 01 02  9F 4D 61 C6 00 00 00 A2  |  .........Ma.....",
        "00 00 00 01 1F 77 01 02  9F 62 C1 36 00 00 00 A2  |  .....w...b.6....",
        "00 00 00 01 F0 F1 01 02  9F 62 C3 92 00 00 00 03  |  .........b......"
    ]
},
"User Data 3": {
    "Section Version": "1",
    "Sub-section type": "1",
    "Created by": "bmc error logging",
    "Data": [
        {
            "CCIN": "2E35",
            "FRU Type": "Normal Hardware FRU",
            "Location Code": "U780C.ND0.WZS002P-P0-C0",
            "Part Number": "00L5665",
            "Priority": "Mandatory, replace all with this type as a unit",
            "Serial Number": "YW30UF18Y00S"
        }
    ]
},